/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function coreVersion(): string

export declare function decryptTextJson(inputJson: string): string

export declare function encryptTextJson(inputJson: string): string

export declare function evaluatePermissionJson(contextJson: string): string

export declare function generateIdentityKeysJson(): string

export declare function verifyEnvelopeJson(envelopeJson: string, signingPublicKey: string): boolean
